config/routes.rb
Rails.application.routes.draw do

  resources :tests
  resources :templates
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users

  root to: 'home#index'

  mount Sidekiq::Web, at: 'sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/template.rb
class Template < ApplicationRecord

  has_many :tests, dependent: :destroy
  validates :title, presence: true, uniqueness: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :template
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # i18n configuration. See: http://guides.rubyonrails.org/i18n.html
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: locale }
  end

  # for devise to redirect with locale
  def self.default_url_options(options = {})
    options.merge(locale: I18n.locale)
  end

  def index; end

  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Username or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/templates_controller.rb
class TemplatesController < InheritedResources::Base

  private

    def template_params
      params.require(:template).permit(:title, :content)
    end
end

app/controllers/tests_controller.rb
class TestsController < InheritedResources::Base

  def new
    @test = Test.new
    @templates = Template.all.order(updated_at: :desc)
    render :new
  end

  def create
    template = Template.find(test_params[:template_id])
    error_indexes = []
    evaluation_splitted = test_params[:evaluation].split
    template.content.split.each_with_index do |element, index|
      error_indexes << index if evaluation_splitted[index] != element
    end
    test = Test.create!(test_params.merge!(error_indexes: error_indexes))
    redirect_to test_path(test.id)
  end

  def show
    @test = Test.find(params[:id])
    @differ = Differ.diff_by_word(@test.template.content, @test.evaluation)
    render :show
  end

  private

    def test_params
      params.require(:test).permit(:template_id, :evaluation, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.slim
.text-center
  h1
    = t('application.index.messages.welcome')

app/views/home/index.html.slim
.col-md-2
.col-md-10
  .row
    h1 Test your Memory!
  .row
    h3 You can create new templates or start evaluating yourself!
  br
  br
  .row
    .col-md-2
      = link_to 'New Template', new_template_path, class: 'btn btn-primary'
    .col-md-2
      = link_to 'Start Test!', new_test_path, class: 'btn btn-success'
    .col-md-2
      = link_to 'View Existing Templates', templates_path, class: 'btn btn-info'

app/views/layouts/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'XX-XXXXXXX-X', 'auto');
  ga('send', 'pageview');

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title MemoryTest
    = csrf_meta_tags
    = metamagic
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/google_analytics'
    .container
      = yield

app/views/templates/_form.html.slim
.col-md-2
.col-md-8
  = form_for @template do |f|
    - if @template.errors.any?
      #error_explanation
        h2 = "#{pluralize(@template.errors.count, "error")} prohibited this template from being saved:"
        ul
          - @template.errors.full_messages.each do |message|
            li = message

    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :content
      = f.text_area :content, class: 'form-control'
    .actions
      = f.submit

.col-md-2

app/views/templates/edit.html.slim
.row.text-center
  h1 Editing template

.row
  == render 'form'

.row
  .col-md-2
  .col-md-10
    = link_to 'Show', @template
    '  |
    = link_to 'Back', templates_path

app/views/templates/index.html.slim
h1 Listing templates

table.table.table-hover
  thead.thead-dark
    tr
      th scope="col" #
      th scope="col" Title
      th scope="col" Content
      th scope="col"
      th scope="col"
      th scope="col"

  tbody
    - @templates.each do |template|
      tr
        th scope="row" = template.id
        td = template.title
        td = template.content
        td = link_to 'Show', template
        td = link_to 'Edit', edit_template_path(template)
        td = link_to 'Destroy', template, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Template', new_template_path
'  |
= link_to 'Back', root_path

app/views/templates/new.html.slim
h1.text-center New template

.row
  == render 'form'
.row
  .col-md-2
  .col-md-8
    = link_to 'Back', root_path
  .col-md-2

app/views/templates/show.html.slim
- if notice.present?
  .row
    p#notice.alert.alert-info = notice
.row
  h3
    | Title
.row
  strong = @template.title.titleize
.row
  h3
    | Content
.row
  = @template.content

br
.row
  = link_to 'Edit', edit_template_path(@template)
  '  |
  = link_to 'Back', root_path

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'  |
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Username
      th Password
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.username
        td = user.password
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Username:
  = @user.username
p
  strong Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
'  |
= link_to 'Back', users_path